package com.example.wearch.lib;

import android.util.Log;

import java.util.ArrayList;
import java.util.Arrays;

public class STATIC {
  public static void log(String mes) {
    Log.i("CUSTOM", mes);
  }

  public static void log(int mes) {
    log(Integer.toString(mes));
  }

  public static void log(boolean mes) {
    log(Boolean.toString(mes));
  }

  public static String htmlUnascape(final String input) {
    Unascape[] unescape = {new Unascape("&#39;", "'"), new Unascape("&quot;", "\""), new Unascape("&amp;", "&")};
    String output = input;
    if (input.contains("&")) {
      for (Unascape anUnescape : unescape) {
        output = output.replaceAll(anUnescape.changer, anUnescape.val);
      }
    }
    return output;
  }

  public static final String MAX_TEXT_WARNING_MESSAGES = "Daha Az gir ulen";
  public static final int MAX_TEXT_SIZE = 15;
  public static final String CRUDE_URL = "https://www.youtube.com/api/timedtext?lang=en&name=&v=";
  public static final String BUILDER_TITTLE = "INTERNET BAGLANTISI GEREKIYOR";
  public static final String BUILDER_MESSAGE = "Bu uygulamayi kullanabilmek icin internet baglantinin olmasi gerekiyor";

  public static void setTimeout(final Runnable runnable, int delay) {
    new android.os.Handler().postDelayed(runnable, delay);
  }
  public static final ArrayList<String> VIDEOS = new ArrayList<>(Arrays.asList(
          "-2Dj9M71JAc",
          "-FOCpMAww28",
          "-Z-vyLHi2us",
          "-aouBn7IKIo",
          "-tOamKtmxdY",
          "-vZXgApsPCQ",
          "0JGarsZE1rk",
          "0K5OO2ybueM",
          "0MD4Ymjyc2I",
          "0ZfSOArXbGQ",
          "0d6iSvF1UmA",
          "0ztdofPc8Rw",
          "1k89OTpDvIU",
          "1o9NEtA2IEQ",
          "2Brajdazp1o",
          "2j00U6lUC-c",
          "2ju61VPdTzw",
          "2wseM6wWd74",
          "2wu28tI9VkM",
          "3B24RaqA33k",
          "3Z6x5t5A9so",
          "3p3-vl9VFYU",
          "3wxBTEo8-T8",
          "4sZdcB6bjI8",
          "5ErKrSyUpEo",
          "5RAJvzV9j-o",
          "5UH7uTpTa44",
          "5Yj3nGv0kn8",
          "6MgDcFlTgVM",
          "6diqpGKOvic",
          "6k8YBJ5sgko",
          "7fx0QcHyrFk",
          "7pVPmmwSeJQ",
          "7uN4I1wEOXE",
          "85hbMtegrLc",
          "8Dv2Hdf5TRg",
          "8KkKuTCFvzI",
          "8_zk2DpgLCs",
          "8nt3edWLgIg",
          "8olL43PKJKw",
          "8woKcr7u-YQ",
          "95ovIJ3dsNk",
          "9AgCr2tTvng",
          "9EVEmZ2c_es",
          "9RTkZaX1cH0",
          "9VF7kffCgJU",
          "9aHusGxntPw",
          "9hltevOHQBw",
          "9qd36_QPxSY",
          "AJg9SXIcPiM",
          "AMVgX8cXsHA",
          "A_xXC37CDSw",
          "AhUhpfKeLus",
          "ApGeDdIaxo8",
          "B4a0NvLTebw",
          "B8ofWFx525s",
          "BOHZHMmTYbk",
          "BPeFy4iyzn0",
          "BXcFEhl7ynM",
          "B_tjKYvEziI",
          "Bs86giWcjLA",
          "BzeTjn0R2VY",
          "C44r6knuJtU",
          "C74amJRp730",
          "CIesJyZUWTY",
          "Cd0JH1AreDw",
          "CdZJ0SMbh10",
          "CsECS5qsGLs",
          "CtvIX4s1bTU",
          "D9ZNpt6FVTY",
          "DDaldVHUedI",
          "DJMhz7JlPvA",
          "DOgsYATbV-s",
          "ERSZb2wHFDw",
          "EZwxKPv1CwA",
          "E_NiCniw0JE",
          "F2hc2FLOdhI",
          "FD5ZKi-moMU",
          "FDhlOovaGrI",
          "FETryXMpDl8",
          "Fb3yp4uJhq0",
          "FktsFcooIG8",
          "Fu_kBW_KSms",
          "GhpFTQfiqCs",
          "H1fvr9rGgSg",
          "H3TF-hI7zKc",
          "HDjM5lw8OYo",
          "HI7zfpitZpo",
          "HNMQ_w7hXTA",
          "HY71088saG4",
          "Hf_zXx09IB8",
          "I_4IK8CiLg8",
          "IjbTiRbeNpM",
          "JnfBXjWm7hc",
          "KCr8s57hdzY",
          "KnCqR2yUXoU",
          "KvBs1fAaKVk",
          "KxLMjn4WPBY",
          "KyamsZXXF2w",
          "LEx6K4P4GJc",
          "LJhklPJz9U8",
          "LN820hIQ17Q",
          "LhszKevcH30",
          "MEDgtjpycYg",
          "MJK-dMlATmM",
          "MNhCvM5pjfs",
          "MnT1xgZgkpk",
          "Mt0PiXLvYlU",
          "MvXZzKZ3JYQ",
          "N2QZM7azGoA",
          "N7wF2AdVy2Q",
          "N9HF8mMe2pU",
          "NDQ1Mi5I4rg",
          "NL0uxDscjdo",
          "NiMgOklgeos",
          "NlYJQ0psZYA",
          "NlpS-DhayQA",
          "O3a9AYu5SUQ",
          "OL8QphMn8jU",
          "Ogce5D2XMZ0",
          "OlLFK8oSNEM",
          "OqUaEJLfrLo",
          "OzA6jRYjVQs",
          "P2AUat93a8Q",
          "P9B8PmUR64U",
          "PYjWLqE_cfE",
          "PaxNc5-qn6s",
          "PsihkFWDt3Y",
          "R1vskiVDwl4",
          "RiM5a-vaNkg",
          "RlQ3C_VanaU",
          "RovaUZY3e8k",
          "S9ry1M7JlyE",
          "SSZG5aPkZyM",
          "Se8kcnU-uZw",
          "Sm5xF-UYgdg",
          "TppG2Wcl3bY",
          "UHkEbemburs",
          "UhXiHJ8vfuk",
          "Un2yBgIAxYs",
          "UpkAqPEcMyE",
          "Urk3xn7l3AM",
          "Us70DN2XSfM",
          "Uwl012o8P7I",
          "UxLRv0FEndM",
          "V48M5j-6zdE",
          "VIgzTLDyObo",
          "VMXdSkW6hns",
          "VbeekjZP-CI",
          "VzyjDR_AWzE",
          "WJo98LfIfEA",
          "WR9Ca5ODE70",
          "WfjzkO6_DEI",
          "XTf9Sdrq1zg",
          "Y6bbMQXQ180",
          "YFC5CwZVCEw",
          "YKACzIrog24",
          "YzGjO5aHShQ",
          "Zd71719_G8Y",
          "Zwwanld4T1w",
          "_7rS_d1fiUc",
          "_GMVTJ9ZKVc",
          "_ltDJynTduY",
          "_rnZaagadyo",
          "_vBggxCNNno",
          "_wMTKRixZIE",
          "_x1qkuvUxuI",
          "a7B39MLVeIc",
          "acikxzM6GaY",
          "arj7oStGLkU",
          "ay-y3tSYGYw",
          "bJ8Kq1wucsk",
          "bJkv9b9o9lo",
          "bKQA6I4BA7o",
          "bNpx7gpSqbY",
          "bVV2Zk88beY",
          "bZsn1_DARRs",
          "buRLc2eWGPQ",
          "c0KYU2j0TM4",
          "c2tOp7OxyQ8",
          "c73Q8oQmwzo",
          "c8WMM_PUOj0",
          "cgxZ4H3gJ8c",
          "coHWLitlm-U",
          "dJEwC4wCM70",
          "dY9f9bFctUE",
          "druJDI6hiiY",
          "e3NA-aKpgFk",
          "eD9F5HdyKqU",
          "eIho2S0ZahI",
          "eMVWSUeeg8A",
          "eVFYhbHpfqU",
          "es4w3WUcrN0",
          "f-Oupk_4VVo",
          "fscaRh2OtXk",
          "fxbCHn6gE3U",
          "g-ONUFFt2qM",
          "gWmRkYsLzB4",
          "gmj-azFbpkA",
          "gyPoqFcvt9w",
          "h9deGh8_tEc",
          "hiIcwt88o94",
          "hv-tFIuhD8E",
          "iE9HMudybyc",
          "iFTWM7HV2UI",
          "iU1bhHeCkoU",
          "j-S03JfgHEA",
          "j4LSwZ05laQ",
          "jM9Q3xP2iBo",
          "j_GzkjHtFiA",
          "k4N2SxUZwiU",
          "k7sKMj85hDw",
          "kTz52RW_bD0",
          "kZP8Kqr_bcw",
          "klUtOqLakpQ",
          "ktOeFgmdIAo",
          "kzdL6GxJ_WY",
          "lWnr-99DNeE",
          "lfBpsV1Hwqs",
          "lkF0TQJO0bA",
          "lwcvhh4pLjE",
          "mCZCok_u37w",
          "mWA2uL8zXPI",
          "mqovAg11q-c",
          "mxNpNuogqsY",
          "nTFEUsudhfs",
          "nbYQ7kdt0U4",
          "nz0cAjXVepg",
          "o8NPllzkFhE",
          "oEIYHTlbeLA",
          "oIGBBPspTKM",
          "ogeGJS0GEF4",
          "pMUv6UWkuWw",
          "pOp-32twRn4",
          "ppZ2WIlRvR8",
          "ptIecdCZ3dg",
          "qKJv4S5peJQ",
          "qYvXk_bqlBk",
          "qp0HIF3SfI4",
          "qxmEpmCtM3o",
          "qzR62JJCMBQ",
          "rThUrXYaneo",
          "raCIUeGUr3s",
          "rftagV38YKY",
          "sNV4yIyXXX0",
          "sR6P5Qdvlnk",
          "sY0Pf_pfqCI",
          "sa1iS1MqUy4",
          "t2gbcVaZ448",
          "t8R_GKS-M2Y",
          "t9c7aheZxls",
          "twWkGt33X_k",
          "u2V0vOFexY4",
          "uKByBgqxOw4",
          "uSUOdu_5MPc",
          "uTL9tm7S1Io",
          "uTbA-mxo858",
          "uebxlIrosiM",
          "uq-6T6TAu74",
          "utV1sdjr4PY",
          "uxDuZs9k8B0",
          "vWJwa7lntTs",
          "vc-n852sv3E",
          "vcxwcWuq7KQ",
          "wJxSRo564Dc",
          "wZ2TF8-PGQ4",
          "waVUm5bhLbg",
          "weWl6PqAdHY",
          "x95nwilkaio",
          "xMj_P_6H69g",
          "xRL2vVAa47I",
          "xYemnKEKx0c",
          "xlUPlxSpDRo",
          "xuAAPsiD768",
          "y9Trdafp83U",
          "yI-8QHpGIP4",
          "yPGwA7t6bpI",
          "ydKcaIE6O1k",
          "yg8SBuTuoKk",
          "yjtCDgjxRAw",
          "z5iw2SeFx2M",
          "zIwLWfaAg-8",
          "zMGE3mbS9NY",
          "zRK9N14Kv-0"
  ));
}

